apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: inventory-app
type: Opaque
data:
  # Base64-encoded strings:
  # DB_PASSWORD: rootpassword
  DB_PASSWORD: cm9vdHBhc3N3b3Jk
  # JWT_SECRET: supersecretjwtkeyforlocalcluster123
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RrZXlmb3Jsb2NhbGNsdXN0ZXIxMjM=
  # CRON_SECRET: secretcron123
  CRON_SECRET: c2VjcmV0Y3JvbjEyMw==
